MyCoinsBaseViews/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import Home

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    #urls apps
    path("",Home.as_view(), name="index"),
    path("account/", include("account.urls", namespace="account")),
    path("despesas/", include("despesas.urls", namespace="despesas")),
    path("receitas/", include("receitas.urls", namespace="receitas")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
]#+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . views import Register,MyLoginView,UpdatePerfil,DetailPerfil
app_name = "account"
urlpatterns = [
    path('register/', Register.as_view(), name="register"),
    path("login/", MyLoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("update/<int:pk>", UpdatePerfil.as_view(), name="update"),
    path("details/<int:pk>", DetailPerfil.as_view(),name="details"),
]

dashboard/urls.py
from django.urls import path
from . views import DashboardView,despesanuais,valores
app_name = "despesas"
urlpatterns = [
    path("dashboardview/", DashboardView.as_view(), name="dashboard"),
    path('despesasanuais/',despesanuais, name="despesasanuais"),
    path('valores/',valores, name="valores"),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import JsonResponse
from despesas.models import Despesa
from receitas.models import Receita
from crum import get_current_user
# Create your views here.

class DashboardView(LoginRequiredMixin, TemplateView):

    template_name = "dashboard/dashboard.html"



def despesanuais(request):
    if request.method == 'GET':
        meses = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        user = request.user
        despesas = Despesa.objects.filter(user=user.id)
        if  len(despesas) > 0:
            valoresPorMEs = []
            for i in meses:
                sum = 0
                for despesa in despesas:
                    if despesa.date.month == i:
                        sum += int(despesa.value)
                valoresPorMEs.append(sum)
            return JsonResponse({'valores': valoresPorMEs, 'meses': meses})
        else:
            return JsonResponse({'msg': "não tem despesas deste ano"})

def valores(request):
    if request.method == 'GET':
        user = request.user
        print(user.username)
        despesas = Despesa.objects.filter(user=user.id)
        receitas = Receita.objects.filter(user=user.id)
        somaDespesa = 0
        somaReceita = 0
        if len(despesas) > 0:
            for despesa in despesas:
                somaDespesa += despesa.value
        if len(receitas) > 0:
            for receita in receitas:
                somaReceita += receita.value
        saldo = somaReceita - somaDespesa
        return JsonResponse({'saldo': saldo})




        

dashboard/templates/dashboard/dashboard.html
{% extends "layouts/base.html" %}
{% block title %} Dashboard {% endblock %}
{% block content %}
<div style="background-color:black;padding:2rem; color:white; border-radius: 5px;box-shadow: 5px 5px 15px rgba(0,0,0,2);margin-bottom: 50px;" class="container"> 
  <div class="center">
    <div  id="saldo">
    </div>
  </div>
    <div class="row align-items-start">
        <div class="col">
          <span style=" display: flex;align-items: center;justify-content: center;"><strong>Despesa por data</strong> </span>
          <form id="form_despesa" style="background-color: #8bc5be;"class="form-control"action="">
            <input class="form-control"type="date" name="date">
            <div class="center">
              <button style="margin-top: 20px; display: flex;align-items: center;justify-content: center;"class="btn btn-primary" type="submit">Enviar</button>
            </div>
          </form>
          
        </div>
        <div class="col">
          <span style=" display: flex;align-items: center;justify-content: center;"><strong>Receita por data</strong> </span>
          <form style="background-color: #8bc5be;" class="form-control"action="">
            <input class="form-control"type="date" name="date">
            <div class="center">
              <button style="margin-top: 20px; display: flex;align-items: center;justify-content: center;"class="btn btn-primary" type="submit">Enviar</button>
            </div>
          </form>
        </div>
        <div class="col">
          <span style=" display: flex;align-items: center;justify-content: center;"><strong>Lucro por data</strong> </span>
          <form style="background-color: #8bc5be;" class="form-control"action="">
            <input class="form-control"type="date" name="date">
            <div class="center">
              <button style="margin-top: 20px; display: flex;align-items: center;justify-content: center;"class="btn btn-primary" type="submit">Enviar</button>
            </div>
          </form>
        </div>
      </div>
      <br>
      <div class="row align-items-center">
        <div class="col">
          <canvas id="despesasanuais"  width="250" height="200"> </canvas>
        </div>
        <div class="col">
          <canvas id="receitasanuais"  width="250" height="200"> </canvas>
        </div>
        <div class="col">
          <canvas id="lucrosanuais"  width="250" height="200"> </canvas>
        </div>
      </div>
</div>
<script>
  window.onload = function(e) {
    saldo("{% url 'dashboard:valores' %}");
  }
</script>
{% endblock %}